# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure-pipelines-marta

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectFolder: 'Time_planner/Time_planner/ClientApp'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd $(projectFolder) && npm install -g @angular/cli && popd
    pushd $(projectFolder) && npm install && popd
    pushd $(projectFolder) && ng build --prod && popd
  displayName: 'npm install and build'
